# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Install core dependencies first
      - pip install --upgrade pip setuptools wheel
      - python -c "import sys; print(sys.path)"

python:
  install:
    - requirements: rtd-requirements.txt
    - method: pip
      path: .
      extra_requirements: []
