coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
        paths:
          - "pymc_marketing"
        branches:
          - main
          - v1.0.0
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 2%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false
