from roadmapper.roadmap import Roadmap
from roadmapper.timelinemode import TimelineMode

roadmap = Roadmap(1200, 800)
roadmap.set_title("CLV Roadmap")
# roadmap.set_subtitle("FEEDBACK REQUESTED")
roadmap.set_timeline(TimelineMode.MONTHLY, start="2024-10-01", number_of_items=5)
roadmap.add_logo("./docs/source/_static/marketing-logo-light.jpg", "top-left", 172, 125)

doc_color = "#70AD47"  # green
model_color = "#4472C4"  # navy blue
util_color = "#ED7D31"  # orange

group_model = roadmap.add_group("Model Development", fill_colour=model_color)
group_doc = roadmap.add_group(
    "Documentation and Notebooks", fill_colour=doc_color, font_colour="black"
)
group_util = roadmap.add_group(
    "Utilities, Plotting, Maintenance", fill_colour=util_color, font_colour="black"
)

task_model = group_model.add_task(
    "Subscription Covariate Model",
    "2024-12-01",
    "2024-12-31",
    fill_colour=model_color,
    font_colour="white",
)
task_model.add_parallel_task(
    "PNBD Seasonality",
    "2025-01-01",
    "2025-02-28",
    fill_colour=model_color,
    font_colour="white",
)

other_model_tasks = {
    "low": [
        "EG Model",
        "EG Covar",
        "sBG Pop",
        "sBG Covar",
        "BG PurProb",
        "BGBB Pred",
        "logp Cache",
        "GG Time Covar",
    ],
    "med": [
        "BG Covar",
        "XR Support",
        "Input Val",
        "PPC Open/Close",
        "BGBB Scan",
        "PNBD Raw Moments",
        "BG Time Covar",
    ],
    "high": ["GG Covar", "BG/NBD Dist Block", "GG Dist Block"],
}

# task.add_milestone("v.1.0", "2024-02-15")
# task.add_milestone("v.1.1", "2024-08-01")

task_util = group_util.add_task(
    "Utility", "2024-10-01", "2024-10-09", fill_colour=util_color, font_colour="black"
)
task_plot = group_util.add_task(
    "Cumulative Plots",
    "2024-10-16",
    "2024-10-31",
    fill_colour=util_color,
    font_colour="black",
)
task_util.add_parallel_task(
    "Seasonality Support",
    "2025-01-01",
    "2025-01-31",
    fill_colour=util_color,
    font_colour="black",
)
task_util.add_parallel_task(
    "PPC Plots", "2024-10-16", "2024-10-31", fill_colour=util_color, font_colour="black"
)
task_plot.add_parallel_task(
    "RFM Plots", "2024-11-15", "2024-11-30", fill_colour=util_color, font_colour="black"
)
task_plot.add_parallel_task(
    "3D Plots", "2024-11-01", "2024-11-15", fill_colour=util_color, font_colour="black"
)


task_docs = group_doc.add_task(
    "RFM Notebook",
    "2024-12-01",
    "2024-12-31",
    fill_colour=doc_color,
    font_colour="black",
)
task_docs.add_parallel_task(
    "BG/BB Notebook",
    "2024-11-01",
    "2024-11-30",
    fill_colour=doc_color,
    font_colour="black",
)
# task_docs = group_doc.add_task("EG Notebook", "2025-09-01", "2025-09-30",fill_colour=doc_color,font_colour="black")
# task_docs.add_parallel_task("Campaign Notebook", "2025-04-01", "2025-04-30",fill_colour=doc_color,font_colour="black")

roadmap.set_footer("Generated by Roadmapper")
roadmap.draw()
roadmap.save("./docs/source/_static/clv_roadmap_2025.png")
